# Generated by Django 5.2.6 on 2025-10-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_order_delivery_address_remove_order_promocode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
